### ISSUE TITLE
SSZ support for endianness

### ISSUE THREAD

**Issue by atoulme** [ConsenSys/cava#101]
There is no support for setting endianness at this time in the SSZ library.
The spec was modified to allow endianness when serializing individual values.

**Comment by cleishm** [comment]
In the current spec, all integers and lengths are serialized in big endian. The other types do not have multi-byte sequences, so I think just doing big-endian is fine.

The spec is probably misleading.

**Comment by atoulme** [comment]
The spec changed - moving from specifying endianness to enforcing integer endianness to little endian.
