### ISSUE TITLE
Can I use these libraries to implement Enterprise Ethereum Client according v2 Spec?

### ISSUE THREAD

**Issue by kant111** [ConsenSys/cava#108]
Hi,

I am wondering if I can I use these libraries to implement Enterprise Ethereum Client according v2 Spec or do I need to fork Ethereum code?

Thanks!

**Comment by atoulme** [comment]
Hello,

You can use those libraries for any purpose you may elect to under the Apache Software License v2.

I guess your question is, are those libraries forming a complete Enterprise Ethereum client?
The answer is no. Cava does not contain an EVM implementation, consensus algorithms or a JSON-RPC interface, nor does it bundle them together as a product. You may want to look at Pantheon from the PegaSys team for this.

HTH!
