### ISSUE TITLE
Bad synchronization?

### ISSUE THREAD

**Issue by hmijail** [ConsenSys/cava#39]
https://github.com/ConsenSys/cava/blob/512b0b66fe23ac4dd192f0fff5e211f79a5c41a5/net/src/main/java/net/consensys/cava/net/tls/FingerprintRepository.java#L56

`addFingerprint()` writes to `fingerprints` with synchronization, but reads it without synchronization through `contains(String, Bytes)`. This seems to be a bug. If asymmetric read/writer locking is wanted, then probably a ReadWriterLock should be used.

**Comment by cleishm** [comment]
Hi @hmijail!

This should be ok as we're avoiding any locks on reading, and the map is never updated - it is only ever replaced (replacing the object reference). Admittedly, it is not currently marked as a volatile reference, so there will be no guarantees that the results of `addFingerprint()` would be immediately visible to other threads, but this is unlikely to be a concern in practice. Still, to alleviate that and also add extra documentation, I've created #40.

Thanks for pointing this out!

**Comment by hmijail** [comment]
Hi again, 

I believe that the new version will behave correctly, but that it's needlessly complicated. I'm trying to understand the use case. Is the goal to avoid concurrently updating a live `HashMap`?

If so, the `synchronized` block is not helping, and actually I'd say it's just being misleading; there is no other `synchronized` block on the same `this`, and so, it is effectively unsynchronized.

I believe that building the new HashMap aside and publishing it with the volatile `fingerprints` variable is enough for correctness. (I am not considering performance)

Apart from that, #40 also adds an `unmodifiableMap`. It's an interesting idea, but then looks like `fingerprints` is first published as a `HashMap`, but after `addFingerprint()` it will suddenly turn into an `unmodifiableMap`. Maybe it'd be more coherent to make `fingerprints` an `unmodifiableMap` from the beginning?

 Relatedly, if we assume that `unmodifiableMap` might have some internal knowledge of the Collections framework, then maybe instead of manually duplicating `HashMap` to update it, a cleaner/more efficient alternative would be to just keep and update the original `HashMap` and just publish a new `unmodifiableMap`.

**Comment by cleishm** [comment]
Hi @hmijail!

Thanks for your interest!

The synchronized block exists to avoid concurrent attempts to write the backing file that contains the host list. If two threads try to add a host concurrently, then they will be serialized. Without that, then they'd both write and one update would vanish when the other does the atomic file replace.

You are correct about #40 and the `unmodifiableMap` inconsistency. The use of `unmodifiableMap` was added in #40 just for safety and to make it obvious that the map is never modified after creation. To be consistent there should also be an unmodifiableMap wrapper in the result of parsing the file in the first place, just as added protection. I've added that in #41.

And no, `unmodifiableMap` doesn't have any magic internal knowledge. It just delegates only read methods to the underlying map and throws on any write methods. If you directly modify the underlying map, then it will appear changed even via the unmodifiable proxy.

Thanks again!

**Comment by hmijail** [comment]
(Deleted and reposting to fix / clarify)

Hi again, 

I believe that the new version will behave correctly, but that it might be needlessly complicated. I'm trying to understand the use case. What is the goal?

1. to avoid updating a live `HashMap` while there might be active readers, with only 1 updater thread
2. to avoid having 2 threads updating `fingerprints` in parallel

For (1), I believe that building the new HashMap aside and publishing it with the volatile `fingerprints` variable is enough for correctness. The `synchronized` block is superfluous.

The `synchronized` block is only helpful for (2). 

Apart from that, #40 also adds an `unmodifiableMap`. It's an interesting idea, but then looks like `fingerprints` is first published as a `HashMap`, but after `addFingerprint()` it will suddenly turn into an `unmodifiableMap`. Maybe it'd be more coherent to make `fingerprints` an `unmodifiableMap` from the beginning?
