### ISSUE TITLE
Most artifacts not on JCenter

### ISSUE THREAD

**Issue by devinrsmith** [ConsenSys/cava#42]
It looks like only cava-toml is making it to JCenter.

http://jcenter.bintray.com/net/consensys/cava/

**Comment by atoulme** [comment]
Thanks for your report @devinrsmith. I am looking into this issue.

**Comment by atoulme** [comment]
In the meantime, you can work around the issue by using the maven repository `http://consensys.bintray.com/consensys/`.

**Comment by atoulme** [comment]
Hello @devinrsmith this issue motivated me to get us synced into Maven Central. To this effect, I have created a maintenance release, 0.3.1.

I am now able to get access to the binaries through Maven Central.
I have been able to use the binaries successfully. They are listed here as well: https://search.maven.org/search?q=cava

I have used those successfully in downstream applications. Please feel free to try out as well and report back.

Closing this issue.

**Comment by devinrsmith** [comment]
Thanks!
