### ISSUE TITLE
Mirror JCenter artifacts to Maven Central

### ISSUE THREAD

**Issue by dnault** [ConsenSys/cava#50]
Makes it easier for the non-Gradle crowd to use your library.

I put this off a long time for my personal projects because I believed it was a hassle, but finally I went though the steps recently and it's really not that bad. It's basically just creating a Jira account and filing some tickets to claim ownership of the artifact ID, then pushing the sync button on the JCenter site.

https://central.sonatype.org/pages/ossrh-guide.html

**Comment by atoulme** [comment]
Hi David,

Thank you for taking the time to document and file this issue!

We have been working towards publishing to Maven Central. Our latest release, 0.3.1, is synced to Maven Central.
You can read more about it here: https://github.com/ConsenSys/cava/issues/42

Would you please try it out and let us know how it goes?

I realize we didn't update the README to point to this new release. I will get on that now.

**Comment by dnault** [comment]
Yup, using 0.3.1 from from Maven Central works like a charm. Thanks!
